# Generated by Django 4.1.3 on 2022-12-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMain', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('cuerpo', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='avatares')),
            ],
        ),
    ]
