# Generated by Django 4.1.3 on 2022-12-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMain', '0004_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='resume',
            field=models.CharField(default='resumen', max_length=50),
        ),
    ]
