# Generated by Django 4.1.3 on 2022-12-31 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppMain', '0006_entrada_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='user',
            field=models.ForeignKey(default='usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
