# Generated by Django 4.1.3 on 2022-12-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
