# Generated by Django 4.1.3 on 2023-01-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
